global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  # prometheus (optional)
  # - job_name: 'prometheus'
  #   static_configs:
  #     - targets: ['localhost:9090']

  # node_exporter
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  # cadvisor
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
