name: build custom docker image for traefik

on:
  push:
    branches:
      - "main"
    paths:
      - "traefik/**"

jobs:
  build-traefik:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the custom Traefik Image
        uses: docker/build-push-action@v2
        with:
          context: ./traefik
          push: true
          tags: ghcr.io/GITHUB-USERNAME/traefik:latest
