name: build custom image for prometheus

on:
  push:
    branches:
      - "master"
    paths:
      - "prometheus/**"

jobs:
  build-prometheus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the custom Prometheus Image
        uses: docker/build-push-action@v2
        with:
          context: ./prometheus
          push: true
          tags: ghcr.io/<GITHUB_USERNAME>/prometheus:latest
