name: build custom image for code-server

on:
  push:
    branches:
      - "master"
    paths:
      - "code-server/**"

jobs:
  build-code-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the custom Code-Server Image
        uses: docker/build-push-action@v2
        with:
          context: ./code-server
          push: true
          tags: ghcr.io/<GITHUB_USERNAME>/code-server:latest
          secrets: |
            "CODE_SERVER_PRIVATE_SSH_KEY_GITHUB=${{ secrets.CODE_SERVER_PRIVATE_SSH_KEY_GITHUB }}"
